### PR TITLE
Import TestGrid UI code with history

### PR DESCRIPTION
**Pull request by michelle192837**
Imports a subset of the code from https://github.com/GoogleCloudPlatform/testgrid that corresponds to the new (MVP) TestGrid UI. Includes the history for these files (but not the rest of the main repo).

Ref #2.

### CODE REVIEW

**Comment by ameukam** [comment]
@michelle192837 cla issue? add personal email to github?

**Comment by michelle192837** [comment]
Reached out to both contributors above for CLA signing! (Thanks in advance folks :D)

**Comment by michelle192837** [comment]
- NOTICE file is no longer needed since everyone has signed the CLA! (Thanks folks! 🎉 )
- Based on offline discussion on K8s Slack, once all the human CLAs (e.g. not google-oss-prow, which is a bot) are covered, we should be good to merge.

**Comment by michelle192837** [comment]
Forcing merge for just this initial PR.

**Pull request merged**
