### PR TITLE
Fix linting issues

### PR DESCRIPTION
**Pull request by ameukam**
Fix some linting issues and improve readability of the codebase

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @michelle192837

**Comment by michelle192837** [comment]
LGTM but quick question: Did you run something specific to update these, or did you go through and fix them manually?

**Comment by ameukam** [comment]
Most manually and with the IDE (neovim).

**Review by michelle192837 — APPROVED** [review]
Neat, thanks!

**Review by michelle192837 — APPROVED** [review]

**Pull request merged**
